# Generated by Django 3.1.7 on 2021-03-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210320_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_price_currency',
        ),
    ]
