# Generated by Django 3.1.7 on 2021-03-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210320_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_price',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
