# Generated by Django 3.1.7 on 2021-03-20 11:45

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_customer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
