# Generated by Django 3.1.7 on 2021-03-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210320_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer_price_currency',
        ),
        migrations.AlterField(
            model_name='product',
            name='customer_price',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
