# Generated by Django 3.1.7 on 2021-03-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210320_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
